In [2]:
# Import SQL Alchemy
from sqlalchemy import create_engine, inspect

# Import pandas
import pandas as pd

In [3]:
realestate=pd.read_csv("Resources/realestate_prices.csv",encoding="latin-1")

In [4]:
realestate.head()

,RegionID,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,1996-04,1996-05,1996-06,...,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05
0,3101,Los Angeles County,CA,Los Angeles-Long Beach-Anaheim,6,37,1,113.0,113.0,113.0,...,422,423,425,427,428,428,428,427,426,425
1,139,Cook County,IL,Chicago-Naperville-Elgin,17,31,2,104.0,105.0,105.0,...,166,166,166,167,168,168,169,170,169,168
2,1090,Harris County,TX,Houston-The Woodlands-Sugar Land,48,201,3,51.0,51.0,51.0,...,98,98,98,99,99,100,101,101,100,100
3,2402,Maricopa County,AZ,Phoenix-Mesa-Scottsdale,4,13,4,62.0,62.0,62.0,...,154,155,156,157,158,159,160,160,160,161
4,2841,San Diego County,CA,San Diego-Carlsbad,6,73,5,104.0,104.0,104.0,...,371,372,374,375,375,375,374,374,374,374

In [5]:
realestate['2000']=realestate[['2000-01','2000-02','2000-03','2000-04','2000-05','2000-06','2000-07','2000-08','2000-09','2000-10','2000-11','2000-12']].mean(axis=1)

In [6]:
realestate['2001']=realestate[['2001-01','2001-02','2001-03','2001-04','2001-05','2001-06','2001-07','2001-08','2001-09','2001-10','2001-11','2001-12']].mean(axis=1)

In [7]:
realestate['2002']=realestate[['2002-01','2002-02','2002-03','2002-04','2002-05','2002-06','2002-07','2002-08','2002-09','2002-10','2002-11','2002-12']].mean(axis=1)

In [8]:
realestate['2003']=realestate[['2003-01','2003-02','2003-03','2003-04','2003-05','2003-06','2003-07','2003-08','2003-09','2003-10','2003-11','2003-12']].mean(axis=1)

In [9]:
realestate['2004']=realestate[['2004-01','2004-02','2004-03','2004-04','2004-05','2004-06','2004-07','2004-08','2004-09','2004-10','2004-11','2004-12']].mean(axis=1)

In [10]:
realestate['2005']=realestate[['2005-01','2005-02','2005-03','2005-04','2005-05','2005-06','2005-07','2005-08','2005-09','2005-10','2005-11','2005-12']].mean(axis=1)

In [11]:
realestate['2006']=realestate[['2006-01','2006-02','2006-03','2006-04','2006-05','2006-06','2006-07','2006-08','2006-09','2006-10','2006-11','2006-12']].mean(axis=1)

In [12]:
realestate['2007']=realestate[['2007-01','2007-02','2007-03','2007-04','2007-05','2007-06','2007-07','2007-08','2007-09','2007-10','2007-11','2007-12']].mean(axis=1)

In [13]:
realestate['2008']=realestate[['2008-01','2008-02','2008-03','2008-04','2008-05','2008-06','2008-07','2008-08','2008-09','2008-10','2008-11','2008-12']].mean(axis=1)

In [14]:
realestate['2009']=realestate[['2009-01','2009-02','2009-03','2009-04','2009-05','2009-06','2009-07','2009-08','2009-09','2009-10','2009-11','2009-12']].mean(axis=1)

In [15]:
realestate['2010']=realestate[['2010-01','2010-02','2010-03','2010-04','2010-05','2010-06','2010-07','2010-08','2010-09','2010-10','2010-11','2010-12']].mean(axis=1)

In [16]:
realestate['2011']=realestate[['2011-01','2011-02','2011-03','2011-04','2011-05','2011-06','2011-07','2011-08','2011-09','2011-10','2011-11','2011-12']].mean(axis=1)

In [17]:
realestate['2012']=realestate[['2012-01','2012-02','2012-03','2012-04','2012-05','2012-06','2012-07','2012-08','2012-09','2012-10','2012-11','2012-12']].mean(axis=1)

In [18]:
realestate['2013']=realestate[['2013-01','2013-02','2013-03','2013-04','2013-05','2013-06','2013-07','2013-08','2013-09','2013-10','2013-11','2013-12']].mean(axis=1)

In [19]:
realestate['2014']=realestate[['2014-01','2014-02','2014-03','2014-04','2014-05','2014-06','2014-07','2014-08','2014-09','2014-10','2014-11','2014-12']].mean(axis=1)

In [20]:
realestate['2015']=realestate[['2015-01','2015-02','2015-03','2015-04','2015-05','2015-06','2015-07','2015-08','2015-09','2015-10','2015-11','2015-12']].mean(axis=1)

In [21]:
realestate['2016']=realestate[['2016-01','2016-02','2016-03','2016-04','2016-05','2016-06','2016-07','2016-08','2016-09','2016-10','2016-11','2016-12']].mean(axis=1)

In [22]:
realestate['2017']=realestate[['2017-01','2017-02','2017-03','2017-04','2017-05','2017-06','2017-07','2017-08','2017-09','2017-10','2017-11','2017-12']].mean(axis=1)

In [23]:
realestate['2018']=realestate[['2018-01','2018-02','2018-03','2018-04','2018-05','2018-06','2018-07','2018-08','2018-09','2018-10','2018-11','2018-12']].mean(axis=1)

In [38]:
new_df=realestate[[
                  'RegionName',
                'State',
                  '2000',
                  '2001',
                  '2002',
                  '2003',
                  '2004',
                  '2005',
                  '2006',
                  '2007',
                  '2008',
                  '2009',
                  '2010',
                  '2011',
                  '2012',
                  '2013',
                  '2014',
                  '2015',
                  '2016',
                  '2017',
                  '2018']].copy()
new_df.head()

,RegionName,State,2000,2001,2002,2003,2004,2005,2006,2007,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Los Angeles County,CA,146.166667,161.500000,186.416667,226.083333,290.000000,353.000000,394.333333,378.833333,...,268.166667,261.000000,247.916667,246.916667,285.000000,316.750000,339.250000,364.000000,392.833333,420.583333
1,Cook County,IL,121.500000,131.250000,142.333333,155.416667,170.833333,190.083333,204.666667,204.583333,...,159.250000,144.250000,129.416667,121.250000,128.083333,137.916667,144.166667,150.833333,157.000000,165.333333
2,Harris County,TX,60.166667,59.166667,60.750000,62.750000,66.833333,69.833333,71.166667,73.500000,...,69.166667,67.916667,66.000000,65.333333,67.750000,72.833333,79.916667,86.250000,91.166667,97.000000
3,Maricopa County,AZ,79.000000,83.833333,88.250000,93.083333,103.500000,142.333333,168.416667,158.083333,...,100.166667,87.833333,78.916667,87.416667,105.583333,115.250000,122.166667,131.333333,140.583333,152.750000
4,San Diego County,CA,150.666667,173.000000,202.166667,242.250000,306.750000,341.833333,337.333333,313.166667,...,230.000000,228.333333,216.083333,217.000000,253.416667,281.083333,298.166667,319.916667,345.000000,369.500000

In [42]:
new_df.set_index('RegionName')
#

,State,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
RegionName,,,,,,,,,,,,,,,,,,,,
Los Angeles County,CA,146.166667,161.500000,186.416667,226.083333,290.000000,353.000000,394.333333,378.833333,318.333333,268.166667,261.000000,247.916667,246.916667,285.000000,316.750000,339.250000,364.000000,392.833333,420.583333
Cook County,IL,121.500000,131.250000,142.333333,155.416667,170.833333,190.083333,204.666667,204.583333,188.333333,159.250000,144.250000,129.416667,121.250000,128.083333,137.916667,144.166667,150.833333,157.000000,165.333333
Harris County,TX,60.166667,59.166667,60.750000,62.750000,66.833333,69.833333,71.166667,73.500000,71.750000,69.166667,67.916667,66.000000,65.333333,67.750000,72.833333,79.916667,86.250000,91.166667,97.000000
Maricopa County,AZ,79.000000,83.833333,88.250000,93.083333,103.500000,142.333333,168.416667,158.083333,129.166667,100.166667,87.833333,78.916667,87.416667,105.583333,115.250000,122.166667,131.333333,140.583333,152.750000
San Diego County,CA,150.666667,173.000000,202.166667,242.250000,306.750000,341.833333,337.333333,313.166667,265.250000,230.000000,228.333333,216.083333,217.000000,253.416667,281.083333,298.166667,319.916667,345.000000,369.500000
Orange County,CA,166.000000,186.083333,213.000000,256.000000,329.166667,377.750000,405.333333,378.500000,318.500000,285.416667,282.666667,266.916667,267.916667,313.000000,338.500000,355.750000,375.500000,397.916667,420.833333
Kings County,NY,171.500000,197.250000,221.500000,257.833333,294.166667,365.166667,402.750000,405.333333,398.916667,369.833333,363.250000,374.000000,376.000000,401.250000,432.000000,469.250000,508.583333,555.166667,592.416667
Miami-Dade County,FL,77.333333,85.250000,98.333333,115.083333,139.000000,174.916667,213.166667,220.333333,180.333333,121.333333,101.083333,96.166667,100.000000,111.916667,129.833333,146.500000,163.166667,180.083333,194.500000
Dallas County,TX,63.416667,65.000000,67.250000,69.500000,74.166667,76.833333,77.833333,78.666667,75.000000,71.333333,70.166667,67.000000,66.583333,69.083333,72.750000,78.250000,88.416667,104.916667,118.750000
Queens County,NY,171.250000,191.166667,208.500000,246.666667,288.416667,342.250000,389.333333,390.916667,369.416667,340.250000,329.916667,324.333333,319.500000,337.916667,369.000000,400.333333,431.833333,464.250000,496.916667
Riverside County,CA,88.833333,98.333333,112.000000,133.916667,175.166667,218.416667,238.083333,217.083333,162.500000,120.583333,115.250000,111.333333,112.166667,134.916667,156.583333,166.833333,176.666667,187.666667,202.000000
San Bernardino County,CA,83.333333,92.000000,105.166667,127.500000,169.666667,217.916667,249.166667,232.750000,175.916667,126.333333,120.250000,113.750000,114.500000,135.750000,159.666667,173.583333,188.583333,204.500000,220.833333
Clark County,NV,83.666667,89.083333,95.583333,105.000000,141.916667,176.500000,187.083333,174.250000,136.000000,94.583333,80.750000,72.416667,72.166667,89.333333,104.250000,112.166667,120.083333,133.333333,154.000000
King County,WA,141.166667,148.416667,154.750000,161.750000,175.916667,202.750000,237.250000,254.416667,240.333333,213.166667,198.416667,180.916667,180.666667,202.500000,223.000000,249.083333,284.166667,330.500000,362.750000
Wayne County,MI,82.333333,90.750000,94.416667,98.916667,104.000000,106.583333,107.083333,99.750000,81.666667,52.250000,35.000000,27.833333,27.000000,31.500000,39.666667,47.166667,52.833333,59.916667,72.666667
Tarrant County,TX,64.333333,63.250000,64.833333,66.416667,70.500000,73.250000,74.916667,76.166667,74.000000,72.166667,72.166667,69.333333,69.000000,71.500000,76.000000,82.000000,90.916667,101.833333,113.166667
Santa Clara County,CA,302.333333,324.166667,325.750000,336.250000,379.583333,451.916667,475.583333,477.666667,428.000000,367.166667,365.250000,348.666667,368.583333,439.166667,492.000000,560.833333,604.916667,669.833333,778.000000
Broward County,FL,78.500000,102.000000,105.083333,118.083333,137.750000,181.916667,209.666667,198.750000,154.333333,109.833333,98.750000,94.416667,95.416667,108.000000,124.416667,136.000000,150.416667,167.166667,181.083333
Bexar County,TX,58.250000,57.166667,58.083333,60.083333,65.333333,69.166667,73.000000,78.500000,78.000000,75.083333,75.000000,73.083333,73.416667,75.250000,78.666667,84.333333,90.083333,97.000000,105.916667
New York County,NY,NaN,NaN,NaN,NaN,NaN,1016.000000,1028.916667,1079.583333,1142.166667,1045.000000,1002.083333,1035.166667,1083.416667,1167.583333,1314.583333,1404.333333,1451.416667,1461.583333,1438.250000
Philadelphia County,PA,41.666667,44.250000,48.416667,53.833333,62.500000,78.500000,90.916667,95.750000,93.750000,89.916667,89.583333,83.750000,80.333333,80.250000,82.666667,85.666667,92.750000,105.083333,117.333333
Alameda County,CA,228.916667,261.000000,274.416667,298.083333,344.083333,414.250000,429.500000,411.333333,343.333333,293.916667,290.333333,268.666667,273.250000,336.000000,387.250000,436.666667,477.916667,521.500000,575.833333
Middlesex County,MA,164.250000,188.833333,208.166667,226.000000,242.583333,258.083333,251.000000,241.083333,227.416667,218.916667,220.916667,214.416667,217.416667,231.083333,245.916667,257.666667,274.416667,297.833333,314.916667
Suffolk County,NY,150.166667,178.500000,211.583333,251.000000,288.750000,335.833333,360.500000,354.250000,330.583333,301.666667,289.833333,274.166667,264.500000,266.500000,279.333333,288.416667,301.333333,324.166667,361.333333
Sacramento County,CA,97.583333,115.583333,133.916667,158.833333,196.750000,239.083333,238.500000,209.166667,160.416667,131.916667,123.666667,109.916667,110.500000,140.000000,160.083333,173.333333,190.750000,210.500000,225.833333
Bronx County,NY,107.333333,116.833333,135.250000,147.083333,167.666667,200.916667,231.583333,244.083333,232.250000,209.500000,203.916667,196.416667,185.000000,195.166667,206.500000,209.583333,222.916667,247.666667,266.416667
Nassau County,NY,168.583333,187.000000,213.750000,246.166667,277.750000,312.083333,327.250000,318.000000,294.500000,265.500000,259.333333,247.583333,242.250000,246.833333,263.333333,277.166667,291.166667,310.583333,336.250000
Palm Beach County,FL,77.166667,84.916667,96.416667,112.583333,136.583333,177.916667,202.583333,181.416667,143.583333,111.750000,101.166667,92.250000,90.750000,101.083333,117.083333,131.083333,145.333333,158.000000,168.250000
Cuyahoga County,OH,80.833333,83.416667,86.000000,89.666667,92.583333,95.333333,94.583333,90.750000,82.250000,76.583333,75.666667,70.000000,67.333333,68.250000,70.250000,71.583333,75.750000,82.500000,88.666667
Hillsborough County,FL,60.166667,66.083333,71.583333,79.083333,91.166667,114.333333,140.250000,135.333333,111.583333,87.916667,78.750000,71.000000,70.083333,76.583333,86.083333,93.750000,105.000000,118.916667,129.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Hall County,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.300000,18.416667,18.250000,19.250000,20.666667,22.083333,23.666667,24.833333,24.583333
Real County,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.500000,50.083333,52.500000,58.500000,60.166667,62.166667,64.000000
Woodson County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.900000,43.750000,39.833333,38.833333,37.416667,36.500000,35.416667,36.083333,35.416667
Rush County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.700000,50.083333,48.083333,44.916667,44.000000,44.583333,44.750000,43.416667,37.833333
Lincoln County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.400000,42.833333,39.583333,38.666667,37.583333,35.583333,34.416667,35.750000,36.416667
Morton County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.100000,52.333333,51.583333,50.666667,46.583333,53.000000,67.500000,74.583333,70.416667
Cochran County,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.700000,33.000000,31.750000,33.166667,36.000000,38.916667,42.666667,46.916667,47.416667
Ness County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.900000,53.750000,52.000000,49.916667,49.750000,49.833333,50.416667,50.833333,47.583333
Granite County,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.000000,128.916667,128.833333,134.833333,140.666667,143.000000,147.166667,152.916667,156.583333
Jewell County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.500000,35.500000,34.333333,34.416667,34.083333,32.500000,30.750000,32.750000,32.500000
Edwards County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.400000,41.916667,39.166667,37.833333,37.000000,38.083333,39.500000,36.250000,32.583333
Trego County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.500000,53.083333,50.750000,49.916667,51.500000,53.500000,53.833333,55.416667,54.416667
Decatur County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.800000,41.750000,42.000000,42.666667,44.000000,47.916667,50.916667,51.250000,48.583333
Fallon County,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.500000,99.666667,100.250000,105.166667,107.750000,110.083333,114.083333,120.083333,140.666667
Elk County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.400000,47.000000,43.666667,40.833333,33.500000,29.250000,27.833333,27.500000,27.500000
Chase County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.400000,53.666667,51.250000,48.000000,45.916667,45.166667,45.583333,45.500000,44.416667
Gove County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.400000,49.916667,49.083333,47.583333,49.083333,52.000000,52.833333,54.750000,51.416667
Hamilton County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.800000,54.583333,54.083333,54.333333,55.916667,64.250000,73.833333,79.583333,74.500000
Graham County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.000000,47.250000,46.416667,46.666667,48.000000,49.500000,49.000000,49.833333,46.583333
Kiowa County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.000000,57.500000,56.833333,58.500000,58.583333,59.583333,62.250000,62.916667,60.333333
Dickens County,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.900000,20.833333,21.083333,21.166667,22.416667,23.583333,24.916667,27.333333,29.500000
Clark County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.500000,46.166667,44.916667,45.166667,40.833333,39.583333,40.750000,41.250000,38.416667
Judith Basin County,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.600000,99.750000,101.166667,106.583333,105.666667,108.666667,115.250000,118.583333,121.916667
Hodgeman County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.400000,53.750000,52.083333,50.666667,50.666667,52.666667,54.666667,55.166667,52.416667
Armstrong County,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.800000,41.583333,42.250000,43.583333,46.000000,48.083333,50.750000,53.000000,50.500000
Comanche County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.000000,41.166667,41.666667,35.666667,32.416667,32.916667,31.333333,29.416667
Daniels County,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.800000,102.916667,103.833333,106.000000,104.416667,110.416667,118.916667,123.500000,118.500000
Lane County,KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.200000,49.000000,47.500000,44.166667,44.500000,45.833333,48.083333,49.583333,45.500000
Prairie County,MT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.800000,100.750000,102.000000,107.500000,111.083333,112.916667,119.083333,111.250000,105.416667
Daggett County,UT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.300000,135.416667,137.500000,147.250000,155.916667,166.000000,184.500000,196.500000,199.500000

In [34]:
new_df.to_csv("Output/price_per_sqft.csv", index=False, header=True)

In [45]:
new_df = pd.melt(new_df, 
        id_vars=['RegionName','State'], 
        value_vars=['2000', '2001',"2002","2003","2004","2005","2006",
                    "2007","2008","2009","2010","2011","2012","2013",
                    "2014","2015","2016","2017","2018"])
new_df.rename(columns={
    "variable":"Year",
    "value":"Price"
})

                  RegionName State  Year       Price
0         Los Angeles County    CA  2000  146.166667
1                Cook County    IL  2000  121.500000
2              Harris County    TX  2000   60.166667
3            Maricopa County    AZ  2000   79.000000
4           San Diego County    CA  2000  150.666667
5              Orange County    CA  2000  166.000000
6               Kings County    NY  2000  171.500000
7          Miami-Dade County    FL  2000   77.333333
8              Dallas County    TX  2000   63.416667
9              Queens County    NY  2000  171.250000
10          Riverside County    CA  2000   88.833333
11     San Bernardino County    CA  2000   83.333333
12              Clark County    NV  2000   83.666667
13               King County    WA  2000  141.166667
14              Wayne County    MI  2000   82.333333
15            Tarrant County    TX  2000   64.333333
16        Santa Clara County    CA  2000  302.333333
17            Broward County    FL  2000   78.500000
18              Bexar County    TX  2000   58.250000
19           New York County    NY  2000         NaN
20       Philadelphia County    PA  2000   41.666667
21            Alameda County    CA  2000  228.916667
22          Middlesex County    MA  2000  164.250000
23            Suffolk County    NY  2000  150.166667
24         Sacramento County    CA  2000   97.583333
25              Bronx County    NY  2000  107.333333
26             Nassau County    NY  2000  168.583333
27         Palm Beach County    FL  2000   77.166667
28           Cuyahoga County    OH  2000   80.833333
29       Hillsborough County    FL  2000   60.166667
...                      ...   ...   ...         ...
32878            Hall County    TX  2018   24.583333
32879            Real County    TX  2018   64.000000
32880         Woodson County    KS  2018   35.416667
32881            Rush County    KS  2018   37.833333
32882         Lincoln County    KS  2018   36.416667
32883          Morton County    KS  2018   70.416667
32884         Cochran County    TX  2018   47.416667
32885            Ness County    KS  2018   47.583333
32886         Granite County    MT  2018  156.583333
32887          Jewell County    KS  2018   32.500000
32888         Edwards County    KS  2018   32.583333
32889           Trego County    KS  2018   54.416667
32890         Decatur County    KS  2018   48.583333
32891          Fallon County    MT  2018  140.666667
32892             Elk County    KS  2018   27.500000
32893           Chase County    KS  2018   44.416667
32894            Gove County    KS  2018   51.416667
32895        Hamilton County    KS  2018   74.500000
32896          Graham County    KS  2018   46.583333
32897           Kiowa County    KS  2018   60.333333
32898         Dickens County    TX  2018   29.500000
32899           Clark County    KS  2018   38.416667
32900    Judith Basin County    MT  2018  121.916667
32901        Hodgeman County    KS  2018   52.416667
32902       Armstrong County    TX  2018   50.500000
32903        Comanche County    KS  2018   29.416667
32904         Daniels County    MT  2018  118.500000
32905            Lane County    KS  2018   45.500000
32906         Prairie County    MT  2018  105.416667
32907         Daggett County    UT  2018  199.500000

[32908 rows x 4 columns]

In [ ]:
new_df =